WebsiteChungKhoan/Controllers/BooksController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WebsiteChungKhoan.Areas.Admin.Controllers;
using WebsiteChungKhoan.Models;

namespace WebsiteChungKhoan.Controllers
{
    public class BooksController : Controller
    {
        // GET: Books
        //Models.Model1 db = new Model1();
        private Model1 db = new Model1();
        public ActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.SapTheoTen = sortOrder == "name_desc" ? "" : "name_desc";
            ViewBag.SapTheoGia = sortOrder == "Gia" ? "gia_desc" : "Gia";
            var list = db.Products.Select(p => p);

            //Phân trang
            

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(p=> p.Name.Contains(searchString));
            }    
            switch (sortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(s => s.Name);
                    break;
                case "Gia":
                    list = list.OrderBy(s => s.Price);
                    break;
                case "gia_desc":
                    list = list.OrderByDescending(s => s.Price);
                    break;
                default:
                    list = list.OrderBy(s => s.Name);
                    break;
            }
            return View(list.ToList());
        }
        public ActionResult DisplaySuplies( int? page)
        {
            var list = db.Products.Select(p => p);
            list = list.OrderBy(p => p.Id_Product);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Details(string id)
        {
            var product = db.Products.FirstOrDefault(p => p.Id_Product == id);

            // Kiểm tra xem sản phẩm có tồn tại không
            if (product == null)
            {
                // Nếu không tìm thấy sản phẩm, trả về trang lỗi hoặc một trang thông báo lỗi khác
                return HttpNotFound(); // hoặc trả về view 404 NotFound
            }

            // Nếu sản phẩm tồn tại, trả về view chi tiết của sản phẩm và truyền thông tin sản phẩm vào view
            return View(product);
        }
            
        

        public ActionResult Detail(string id) 
        {
            var product = db.Products.FirstOrDefault(p => p.Id_Product == id);

            // Kiểm tra xem sản phẩm có tồn tại không
            if (product == null)
            {
                // Nếu không tìm thấy sản phẩm, trả về trang lỗi hoặc một trang thông báo lỗi khác
                return HttpNotFound(); // hoặc trả về view 404 NotFound
            }

            // Nếu sản phẩm tồn tại, trả về view chi tiết của sản phẩm và truyền thông tin sản phẩm vào view
            return View(product);
        }
    }
}

WebsiteChungKhoan/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteChungKhoan.Controllers
{
    public class CartsController : Controller
    {
        // GET: Carts
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

WebsiteChungKhoan/Views/Books/Detail.cshtml
@model WebsiteChungKhoan.Models.Product

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Details</title>
    <!-- Include các file CSS của Bootstrap nếu cần -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Product Details</h1>
        <hr>
        <div>
            <dl class="dl-horizontal">
                <dt>Name:</dt>
                <dd>@Model.Name</dd>

                <dt>Price:</dt>
                <dd>@Model.Price VNĐ</dd>

                <dt>Quantity:</dt>
                <dd>@Model.Quantity</dd>

                <dt>Image:</dt>
                <dd><img src="@Url.Content(Model.Img)" alt="Product Image" style="max-width: 200px;"></dd>

                <dt>Description:</dt>
                <dd>@Model.Description</dd>
            </dl>
        </div>
        <p>
            <!-- Điều hướng trở lại danh sách sản phẩm hoặc chỉnh sửa sản phẩm -->
            <a href="@Url.Action("Index", "Books")" class="btn btn-primary">Back to Product List</a>
            <a href="@Url.Action("Index", "Carts", new { id = Model.Id_Product })" class="btn btn-secondary">Thêm Vào Giỏ Hàng</a>
        </p>
    </div>

    <!-- Include các file script của Bootstrap và các thư viện khác nếu cần -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

WebsiteChungKhoan/Views/Books/DisplaySuplies.cshtml
@model PagedList.IPagedList<WebsiteChungKhoan.Models.Product>
@using PagedList.Mvc;

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Author.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reciept.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Star.Id_Star)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Author.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reciept.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Star.Id_Star)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Img)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id_Product }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id_Product }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id_Product })
            </td>
        </tr>
    }

</table>

WebsiteChungKhoan/Views/Books/Index.cshtml
@model IEnumerable<WebsiteChungKhoan.Models.Product>


<style>
    
    .dropbtn {
        background-color: #444;
        color: white;
        padding: 10px 14px;
        font-size: 15px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        margin-bottom: 5px;
        transition-duration: .3s;
    }

        .dropbtn:after {
            /* kí tự mũi tên > */
            content: ' \25B7';
        }

    .dropdown:hover .dropbtn:after {
        /* kí tự mũi tên xuống */
        content: ' \25BD'
    }

    .dropdown {
        position: relative;
        margin: 10px 5px;
    }

    .dropdown-content {
        z-index: 1;
        position: absolute;
        min-width: 170px;
        border-radius: 5px;
        background-color: rgba(255, 255, 255, .8);
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.5);
        /* mặc địng là xoay 90 độ => bị ẩn đi */
        transform: rotateX(90deg);
        transition-duration: .3s;
    }

        .dropdown-content a {
            color: #444;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

            .dropdown-content a:hover {
                color: white;
                background-color: #555
            }

    .dropdown:hover .dropdown-content {
        /* khi hover vào thì cần hiện content ra => xoay 0 độ => trờ về như cũ */
        transform: rotateY(0deg);
    }

    .dropdown:hover .dropbtn {
        background-color: #3e8e41;
    }
    #khongCoSanPham {
        opacity: 0;
        width: 0;
        color: red;
        font-size: 30px;
        font-weight: bold;
        height: 310px;
    }
    /* Home Product */
    .homeproduct {
        list-style-type: none;
    }

    /* <li> trong homeproduct có class="sanPham" , khai báo trong classes.js */
    .sanPham {
        width: 238px;
        border: 1px solid #eee;
        -webkit-transition-duration: .3s;
        -o-transition-duration: .3s;
        transition-duration: .3s;
    }

        .sanPham a {
            display: block;
            position: relative;
            padding: 10px 0;
            height: 310px;
        }

            .sanPham a .price span {
                display: inline-block;
                vertical-align: middle;
                font-size: 12px;
                text-decoration: line-through;
                margin-left: 5px;
                color: #222;
            }
            /* Name and image */
            /* Hinh anh san pham */
            .sanPham a img {
                display: block;
                margin: 15px auto;
                -webkit-transition-duration: 0.2s;
                -o-transition-duration: 0.2s;
                transition-duration: 0.2s;
                width: 200px;
                height: 200px;
            }
            /* Di chuyen anh? len tren */
            .sanPham a:hover > img {
                margin: 5px auto 25px;
            }
        /* Ten san pham */
        .sanPham h3 {
            display: block;
            padding: 0 10px;
            color: #333;
            line-height: 1.3em;
            font-size: 15px;
            font-weight: normal;
        }
        /* Hightlight ten san pham khi hover */
        .sanPham a:hover h3 {
            color: #288ad6;
        }
        /* ====== End Name and image ===== */

        /* Price */
        /* la div chua strong */
        .sanPham .price {
            display: block;
            padding: 5px 10px 0px 10px;
        }
        /* strong la gia tien in dam */
        .sanPham strong {
            display: inline-block;
            vertical-align: middle;
            overflow: hidden;
            font-size: 14px;
            color: #e10c00;
            line-height: 15px;
        }
        /* ===== End Price ===== */

        /* Rating */
        .sanPham .ratingresult {
            padding: 5px 10px;
        }

            .sanPham .ratingresult span {
                display: inline-block;
                /*position: relative;*/
                top: 1px;
                margin-left: 5px;
                vertical-align: middle;
                text-decoration: none;
                font-size: 12px;
                color: #777;
            }

    .fa-star, .fa-star-o {
        color: orange;
    }
    /* ===== End Rating ===== */

    /* Khuyen mai */
    /* label la tag khuyen mai */
    .sanPham label {
        display: inline-block;
        position: absolute;
        top: 207px;
        left: 10px;
        font-size: 12px;
        color: #fff;
        font-weight: 600;
        border-radius: 2px;
        padding: 3px 5px 0;
        height: 18px;
    }
        /* Giam gia thanh */
        .sanPham label.giamgia {
            background-image: -webkit-gradient(linear, left top, right top, from(#ff9c00), to(#ec1f1f));
            background-image: -webkit-linear-gradient(left, #ff9c00 0%, #ec1f1f 100%);
            background-image: -o-linear-gradient(left, #ff9c00 0%, #ec1f1f 100%);
            background-image: linear-gradient(90deg, #ff9c00 0%, #ec1f1f 100%);
            border-radius: 10px;
            padding: 1px 7px;
            padding-left: 0;
            padding-right: 10px;
        }
    /* Kí tự sấm sét */
    .fa-bolt {
        width: 20px;
        height: 20px;
        text-align: center;
        line-height: 20px;
        border-radius: 50%;
        background: #f21;
        color: white;
    }
    /* Tra gop 0% */
    .sanPham label.tragop {
        background: #f28902;
    }
    /* Gia re online */
    .sanPham label.giareonline {
        background: #3fb846;
    }
    /* Moi ra mat */
    .sanPham label.moiramat {
        background: #1191f8;
    }
    /* ===== End Khuyen mai ====== */

    /* ===== Them Vao Gio Hang ==== */
    /* tooltip được css bên style.css */
    .themvaogio {
        z-index: 20;
        border: 1px solid #e3e7eb;
        border-radius: 50%;
        width: 1.5em;
        height: 1.5em;
        font-size: 1.5em;
        color: rgb(163, 161, 161);
        background: none;
        transition-duration: .2s;
        cursor: pointer;
    }

        .themvaogio:hover {
            color: black;
            background-color: #e6e6e6;
            box-shadow: 0px 8px 10px 0px rgba(0,0,0,0.2);
        }

        .themvaogio:active {
            box-shadow: none;
        }
    .products{
        width: 100%;
        display: flex;
    }
    .products .sanPham {
        display: block;
    }
    .input-search button {
        float: right;
        font-size: 14px;
        font-weight: bold;
        padding: 0 10px;
        color: #888;
        background: none;
        width: 100px;
        height: 100%;
        border: none;
        cursor: pointer;
        -webkit-transition-duration: .3s;
        -o-transition-duration: .3s;
        transition-duration: .3s;
    }
    /* ===== End Them Vao Gio Hang ==== */
    /* ====== End Home Product ======= */
</style>
<div class="container">
    <div class="row">
        @using (Html.BeginForm())
            {
                <p>
                    Tìm Mặt hàng : @Html.TextBox("searchString");
                    <input type="submit" value="Tìm" />
                </p>
            }
        @*<div class="autocomplete">
            <input id="search-box" name="search" autocomplete="off" type="text" placeholder="Nhập từ khóa tìm kiếm...">
            <button type="submit">
                <i class="fa fa-search"></i>
                Tìm kiếm
            </button>
        </div>*@
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="sortFilter dropdown">
                <button class="dropbtn">Sắp xếp</button>
                <div class="dropdown-content">
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.SapTheoTen })">Tên Tăng Dần</a>
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.SapTheoGia })">Giá Tăng Dần</a>
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.SapTheoTen == "name_desc" ? "" : "name_desc" })">Tên Giảm Dần</a>
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.SapTheoGia == "gia_desc" ? "Gia" : "gia_desc" })">Gái Giảm Dần</a>

                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <ul id="products" class="homeproduct group flexContain">
        @foreach (var item in Model)
        {
                <li class="sanPham">
                    <a href="/Books/Detail/@item.Id_Product">
                        <img  src="@Url.Content(item.Img)" alt="Not Img">
                        <h3>@item.Name</h3>
                        <div class="price">
                            <strong>@item.Price</strong>
                        </div>
                        <div class="ratingresult">
                            <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><span>2 đánh giá</span>
                        </div>
                        <label class="moiramat">
                            Mới ra mắt
                        </label>
                        <div class="tooltip">
                            <button class="themvaogio">
                                <span class="tooltiptext" style="font-size: 15px;">Thêm vào giỏ</span>
                                +
                            </button>
                        </div>
                    </a>
                </li>
                <!-- End Khong co san pham -->
        }
            </ul>
        </div>
    </div>
    
</div>